-- Template: babysitter_scoped_read
-- Parameters: __TABLE__, __FAMILY_COL__, __BABYSITTER_FLAG_COL__ (boolean — when true, babysitters may read the row)
-- Intent: full members see all rows; babysitters only see rows explicitly flagged for them.
--
-- Tokenized babysitter guests (Phase 2.5): combine row flags with resources returned from
-- `public.babysitter_scope(raw_token)` when routing through link-based identities.
--
-- Example (SELECT):
--   USING (
--     public.is_member_of(__TABLE__.__FAMILY_COL__)
--     and (
--       not public.babysitter_can_read(__TABLE__.__FAMILY_COL__)
--       or __TABLE__.__BABYSITTER_FLAG_COL__
--     )
--   )
--
-- public.babysitter_can_read mirrors has_role(..., babysitter); combine with a per-row gate column.
