// ignore_for_file: avoid_print

/// Regenerates:
/// - `lib/src/policy/capability_matrix_generated.dart`
/// - Seeds inside `supabase/migrations/20260512000210_capability_matrix.sql`
///
/// Usage (from repo root): `dart run packages/autolife-core/tool/generate_policy_matrix.dart`
/// Or from `packages/autolife-core`: `dart run tool/generate_policy_matrix.dart`
library;

import 'dart:convert';
import 'dart:io';

import '../lib/src/policy/matrix_model.dart';

void main(List<String> args) {
  final pkgRoot = File(
    Platform.script.toFilePath(),
  ).absolute.parent.parent.path;

  final yamlFile = File(
    '$pkgRoot${Platform.pathSeparator}policy${Platform.pathSeparator}matrix.yaml',
  );
  final migrationPath =
      '${Directory(pkgRoot).parent.parent.path}'
      '${Platform.pathSeparator}supabase${Platform.pathSeparator}migrations'
      '${Platform.pathSeparator}20260512000210_capability_matrix.sql';
  final outDart = File(
    '$pkgRoot${Platform.pathSeparator}lib${Platform.pathSeparator}'
    'src${Platform.pathSeparator}policy${Platform.pathSeparator}capability_matrix_generated.dart',
  );

  final yamlSrc = yamlFile.readAsStringSync();
  final parsed = parsePolicyMatrixYaml(yamlSrc);
  final canonDartLiteral = json.encode(policyMatrixCanonicalJson(yamlSrc));

  final dartBuf = StringBuffer()
    ..writeln("// GENERATED by tool/generate_policy_matrix.dart — do not edit.")
    ..writeln()
    ..writeln("import 'capability_grant_defaults.dart';")
    ..writeln()
    ..writeln(
      '/// Canonical JSON (sorted) derived from [policy/matrix.yaml]. Drift checks in CI/tests.',
    )
    ..writeln('const String kPolicyMatrixCanonicalJson = $canonDartLiteral;')
    ..writeln()
    ..writeln(
      '/// Default template rows keyed by capability wire, then family_role wire.',
    )
    ..writeln(
      'const Map<String, Map<String, CapabilityGrantDefaults>> kGeneratedCapabilityLookup = {',
    );

  final byCapability = <String, List<MatrixRow>>{};
  for (final r in parsed.rows) {
    byCapability.putIfAbsent(r.capability, () => []).add(r);
  }
  final caps = byCapability.keys.toList()..sort();
  var firstCap = true;
  for (final cap in caps) {
    if (!firstCap) {
      dartBuf.writeln(',');
    }
    firstCap = false;
    dartBuf.writeln("  '${_escapeDart(cap)}': {");
    final roleRows = byCapability[cap]!
      ..sort(
        (a, b) => compareFamilyRoleWire(a.familyRoleWire, b.familyRoleWire),
      );
    var firstRole = true;
    for (final row in roleRows) {
      if (!firstRole) dartBuf.writeln(',');
      firstRole = false;
      dartBuf.write(
        "    '${_escapeDart(row.familyRoleWire)}': "
        'CapabilityGrantDefaults('
        'granted: ${row.granted}, '
        'requiresParentApproval: ${row.requiresParentApproval}, '
        'requirePhotoProof: ${row.requirePhotoProof}, '
        'requireParentVerification: ${row.requireParentVerification})',
      );
    }
    dartBuf.writeln();
    dartBuf.write('  }');
  }
  dartBuf.writeln();
  dartBuf.writeln('};');

  outDart.writeAsStringSync('$dartBuf\n');

  final sqlInserts = StringBuffer()
    ..writeln('insert into public.capability_matrix_default (')
    ..writeln('  role,')
    ..writeln('  capability,')
    ..writeln('  granted,')
    ..writeln('  requires_parent_approval,')
    ..writeln('  require_photo_proof,')
    ..writeln('  require_parent_verification')
    ..writeln(')')
    ..writeln('values ');
  final sortedRows = parsed.rows.toList()
    ..sort((a, b) {
      final c = compareFamilyRoleWire(a.familyRoleWire, b.familyRoleWire);
      if (c != 0) return c;
      return a.capability.compareTo(b.capability);
    });
  for (var i = 0; i < sortedRows.length; i++) {
    final r = sortedRows[i];
    sqlInserts.write(
      "  ('${r.familyRoleWire}'::family_role, "
      "'${_escapeSql(r.capability)}', "
      '${r.granted}, '
      '${r.requiresParentApproval}, '
      '${r.requirePhotoProof}, '
      '${r.requireParentVerification})',
    );
    if (i < sortedRows.length - 1) {
      sqlInserts.writeln(',');
    } else {
      sqlInserts.writeln();
    }
  }
  sqlInserts.writeln('on conflict (role, capability) do update set');
  sqlInserts.writeln('  granted = excluded.granted,');
  sqlInserts.writeln(
    '  requires_parent_approval = excluded.requires_parent_approval,',
  );
  sqlInserts.writeln('  require_photo_proof = excluded.require_photo_proof,');
  sqlInserts.writeln(
    '  require_parent_verification = excluded.require_parent_verification;',
  );

  _patchMarkers(
    migrationFile: File(migrationPath),
    markerBegin: '-- @autolife-codegen:policy-matrix-seed-begin',
    markerEnd: '-- @autolife-codegen:policy-matrix-seed-end',
    body: '$sqlInserts',
  );

  print('Updated ${outDart.path}');
  print('Patched markers in $migrationPath');
}

String _escapeDart(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

String _escapeSql(String s) => s.replaceAll("'", "''");

void _patchMarkers({
  required File migrationFile,
  required String markerBegin,
  required String markerEnd,
  required String body,
}) {
  if (!migrationFile.existsSync()) {
    throw StateError('Missing migration: ${migrationFile.path}');
  }
  final text = migrationFile.readAsStringSync();
  final i1 = text.indexOf(markerBegin);
  final i2 = text.indexOf(markerEnd);
  if (i1 < 0 || i2 < 0 || i2 <= i1) {
    throw StateError('Markers not found in ${migrationFile.path}');
  }
  final keptStart = text.substring(0, i1 + markerBegin.length);
  final keptEnd = text.substring(i2);
  final combined = '$keptStart\n$body\n$keptEnd';
  migrationFile.writeAsStringSync(combined);
}
